name: player
version: 0.0.1

publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.24.0
  screen: 
  video_player:
    git:
      url: https://github.com/fastogt/plugins.git
      ref: master
      path: packages/video_player/video_player

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1

